name: Verificar Proyecto

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  validar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Verificar frontend/index.html
        run: test -f frontend/index.html

      - name: Verificar frontend/style.css
        run: test -f frontend/style.css

      - name: Verificar backend/app.py
        run: test -f backend/app.py

      - name: Verificar requirements.txt
        run: test -f backend/requirements.txt

      - name: Verificar README
        run: test -f README.md

      - name: Verificar docker-compose
        run: test -f docker-compose.yml
